import React from 'react'
import bgImg from "./images/T-C.webp"
import "./T_C.css"

const T_C = () => {
    return (
        <>
            <div className="login_BgImg">
                <img src={bgImg} alt="img" />
            </div>


            <div className='loginContainer T_C_Container'>
                <h1>BENGALURU FC USER TERMS AND CONDITIONS</h1>


                <div >
                    <p></p>
                    <ul>
                        <li>
                            <span class="bold">INTRODUCTION</span><p></p>
                            <ol class="pl-0">
                                <li>
                                    This page sets out the terms and conditions (“<span class="bold">User Terms</span>”) which govern the use of the website www.bengalurufc.com (“<span class="bold">Website</span>”) which you shall be deemed to have read, understood, and consented to of your free will. These User Terms are supplemented by the Privacy Policy of the Website which can be accessed here <a href="https://www.bengalurufc.com/privacy-policy/" data-slimstat="5">https://www.bengalurufc.com/privacy-policy</a>.
                                </li>
                                <li>
                                    The Website is owned and operated by JSW Bengaluru Football Club Pvt Ltd (hereinafter referred to as “<span class="bold">we</span>”, “<span class="bold">us</span>”, or “<span class="bold">Company</span>”). The Company is a private limited company registered under the Companies Act, 1956, bearing Company Identification Number U92412KA2012PTC075013 and having its registered office at 6th Floor, Raheja Towers (East), 26-27, M. G. Road,Bangalore – 560001, Karnataka, INDIA.
                                </li>
                                <li>
                                    The User Terms and the Privacy Policy are between the Company and users of the Website (hereinafter referred to as “<span class="bold">you</span>”, “<span class="bold">your</span>” or “<span class="bold">User</span>”), and describe the terms on which the Company offers you access to the Website and the services availed through use of the Website (the “<span class="bold">Services</span>”).
                                </li>
                                <li>
                                    We reserve the right to modify / update the whole or any part of the User Terms and / or Privacy Policy at any time without providing prior notice to you. It is your responsibility to review the User Terms (including the Privacy Policy) periodically for modifications / updates. Your continued use of the Website will mean that you accept and agree to be bound by such modified / updated User Terms (including Privacy Policy). As long as you comply with the User Terms and Privacy Policy, we grant you a personal, non-exclusive, non-transferable, and limited privilege to enter and use the Website.
                                </li>
                                <li>
                                    The User Terms are an electronic record in terms of the Information Technology Act, 2000, the applicable rules thereunder (as amended from time to time) and the provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000 and are published in accordance with the provisions of Rule 3(1) of the Information Technology (Intermediaries Guidelines) Rules, 2011. This electronic record is generated by a computer system and does not require any physical or digital signature.
                                </li>
                            </ol>
                        </li>
                        <li>
                            <span class="bold">BINDING CONTRACT</span><p></p>
                            <ol class="pl-0">
                                <li>
                                    The User Terms and the Privacy Policy collectively constitute the entire contract between the User(s) and the Company with respect to the Services, superseding any prior written or oral contracts in relation to the subject matter herein. By browsing the Website and / or using any of the Services, you signify your acceptance of the User Terms and Privacy Policy which take effect on the date on which you browse the Website and / or use the Services and create a legally binding arrangement to abide by the same. By accepting the User Terms and Privacy Policy, you also accept and agree to be bound by Company’s policies, as amended, from time to time.
                                </li>
                                <li>
                                    PLEASE READ THE USER TERMS AND PRIVACY POLICY CAREFULLY BEFORE USING OR REGISTERING ON THE WEBSITE OR ACCESSING ANY SERVICE. IF YOU DO NOT AGREE WITH THE USER TERMS AND PRIVACY POLICY, PLEASE DO NOT USE THE WEBSITE OR THE SERVICES.
                                </li>
                            </ol>
                        </li>
                        <li>
                            <span class="bold">ELIGIBILITY FOR USE</span><p></p>
                            <ol class="pl-0">
                                <li>
                                    The use of the Services is available only to those individuals who can enter into legally binding contracts under applicable laws of India. Persons who are incompetent to contract under applicable laws of India are not eligible to avail the Services.
                                </li>
                                <li>
                                    By using the Website, you warrant and confirm that you have the legal right, authority, and capacity to enter into and be bound by the User Terms and the Privacy Policy.
                                </li>
                            </ol>
                        </li>
                        <li>
                            <span class="bold">USER ACCOUNTS</span><p></p>
                            <ol class="pl-0">
                                <li>
                                    In order to avail the Services through the Website, you would be required to register by creating a user account via the Website. During the registration process you will be invited to choose a desired username and password which will be unique to you.
                                </li>
                                <li>
                                    You agree and confirm that you shall: (a) provide accurate, truthful, current and complete information while creating your account; and (b) in all your dealings through the Website (i) maintain and promptly update your account information, (ii) maintain the security of your account by not sharing your password with others and restricting access to your account and your device, (iii) promptly notify the Company if you discover or otherwise suspect any security breaches relating to your account or the Website, and (iv) take responsibility for all activities that occur under your account and accept all risk of unauthorized access to the same. By registering, accessing, or using the Website, the User accepts the User Terms and the Privacy Policy in totality.
                                </li>
                                <li>
                                    The Company reserves the right (but shall not be obliged) to confirm and validate the information and other details provided by you in the course of your use of the Website. If upon such confirmation any details furnished by you are found, or are reasonably believed, to be inaccurate, false, misleading, or fraudulent, the Company shall, in its sole discretion, have the right to reject your registration and debar you from using the Services without any intimation to you and the Company assumes no responsibility and shall not be liable for, any such act on its part.
                                </li>
                                <li>
                                    In the event the system is unable to establish unique identity of the User against a valid mobile number or e-mail ID, the user account shall be indefinitely suspended by the Company without any liability on its part, whatsoever.
                                </li>
                            </ol>
                        </li>
                        <li>
                            <span class="bold">SUBMISSION OF INFORMATION </span><p></p>
                            <ol class="pl-0">
                                <li>
                                    The Company authorizes you to access the Website solely for the purpose of using the Services.
                                </li>
                                <li>
                                    You hereby authorize the Company to (i) use your submitted information to contact you, (ii) maintain a record of your queries, visit of the Website, and/or feedback, and (iii) subject to applicable laws of India, use all submitted information by you in a manner as it may deem necessary to make the Services available to Users.
                                </li>
                                <li>
                                    You shall not post any content or offer or information which is false, deceptive, misleading, deceitful, and / or mis-informative.
                                </li>
                                <li>
                                    For certain function of the Services, such as reviewing and tracking your use of the Services or to provide effective Services through the Website, you may be required to provide your name, age, mobile or phone number, and / or address; without limiting the generality of the foregoing, you are required to provide accurate and complete information to be able to avail the Services.
                                </li>
                                <li>
                                    The Company reserves the right, at its sole discretion, to suspend your ability to use or access the Website (or a part thereof) or the Services at any time while the Company investigates complaints or alleged violations of the User Terms or the Privacy Policy. Further, it shall also have the ability to prohibit or restrict you from using the Website if the Company (i) in its reasonable opinion, feels that either you are misusing the Website in any manner whatsoever; or (ii) discovers an external threat to your registered account which could lead to misuse of your account or information provided by you.
                                </li>
                            </ol>
                        </li>
                        <li>
                            <span class="bold">USER COVENANTS </span><p></p>
                            <ol class="pl-0">
                                <li>
                                    By using any of the Services you agree and acknowledge that: <p></p>
                                    <ul >
                                        <li>
                                            (a)	You will use any or all the Services provided by the Company only for the purposes that are permitted by (i) the User Terms and Privacy Policy, and (ii) any applicable law, and not for any fraudulent purposes or with a view to cause nuisance, annoyance, or inconvenience to any person.
                                        </li>
                                        <li>
                                            (b)	All calls made to the Company will be recorded by the Company for quality and training purposes.
                                        </li>
                                        <li>
                                            (c)	You are solely responsible for any breach of the User Terms and Privacy Policy and for the consequences resulting from such breach (including any loss, damage or expense suffered or incurred by the Company or its affiliates / business partners / vendors).
                                        </li>
                                    </ul>
                                </li>
                                <li>
                                    As mandated by Regulation 3(2) of the Information Technology (Intermediaries Guidelines) Rules, 2011, and to the extent it is applicable to the User Terms and Privacy Policy, the Company hereby informs you that you are not permitted to host, display, upload, modify, publish, transmit, update, or share any information that: <p></p>
                                    <ul >
                                        <li>
                                            (a)	belongs to another person and to which you do not have any right;
                                        </li>
                                        <li>
                                            (b)	is grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic, paedophilic, libellous, invasive of another’s privacy, hateful, or racially, ethnically objectionable, disparaging, relating to or encouraging money laundering or gambling, or otherwise unlawful in any manner whatsoever;
                                        </li>
                                        <li>
                                            (c)	harms minors in any way;
                                        </li>
                                        <li>
                                            (d)	infringes any patent, trademark, copyright, or other proprietary rights;
                                        </li>
                                        <li>
                                            (e)	violates any law for the time being in force;
                                        </li>
                                        <li>
                                            (f)	deceives or misleads the addressee about the origin of such messages or communicates any information which is grossly offensive or menacing in nature;
                                        </li>
                                        <li>
                                            (g)	impersonates or defames another person;
                                        </li>
                                        <li>
                                            (h)	contains software viruses or any other computer code, files or programs designed to interrupt, destroy, or limit the functionality of any computer resource; and
                                        </li>
                                        <li>
                                            (i)	threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any cognisable offence or prevents investigation of any offence or is insulting to any other nation.
                                        </li>
                                    </ul>
                                </li>
                                <li>
                                    You are also prohibited from: <p></p>
                                    <ul >
                                        <li>
                                            (a)	violating or attempting to violate the integrity or security of the Website;
                                        </li>
                                        <li>
                                            (b)	transmitting any information on or through the Website that is disruptive to the provision of the Services provided by the Company;
                                        </li>
                                        <li>
                                            (c)	intentionally submitting on the Website any incomplete, false, or inaccurate information;
                                        </li>
                                        <li>
                                            (d)	making any unsolicited communications to other users of the Website;
                                        </li>
                                        <li>
                                            (e)	attempting to decipher, decompile, disassemble, or reverse engineer any part of the Website;
                                        </li>
                                        <li>
                                            (f)	copying or duplicating in any manner any of the information available on the Website; and
                                        </li>
                                        <li>
                                            (g)	framing or hotlinking or deep linking any contents from the Website.
                                        </li>
                                    </ul>
                                </li>
                                <li>
                                    The Company, upon obtaining knowledge by itself or having been brought to actual knowledge by an affected person in writing or through email about any such information as mentioned in clause 6.2 and / or clause 6.3 above, shall be entitled to disable such information that is in contravention of clause 6.2 or clause 6.3 and the Company shall be entitled to preserve such information and associated records for production to governmental authorities for investigation purposes.
                                </li>
                            </ol>
                        </li>
                        <li>
                            <span class="bold">THIRD PARTY SERVICES AND INFORMATION</span><p></p>
                            <ol class="pl-0">
                                <li>
                                    The Website or the Services may provide information regarding third party website(s), mobile applications, affiliates, or business partners and / or contain links to their websites. Such information and links are provided solely for the purpose of your reference. The Company is not endorsing third party material on the Website or through the Services, is not responsible for such errors and representation nor is it associated with it and you shall access these third party websites at your own risk. Further, it is up to you to take precautions to ensure that whatever links you select or software you download from the Website, is free of such items such as, but not limited to, viruses, worms, trojan horses, defects, and other items of a destructive nature.
                                </li>
                                <li>
                                    In certain cases, the Website may also host services which are provided by third parties (“<span class="bold">Third Party Services</span>”) or provide options to its Users to use Third Party Services via the Website. In such cases, you agree that you shall be subject to adhere to the terms and conditions of the Third Party Services framed by the third party service providers (“<span class="bold">Third Party Providers</span>”).
                                </li>
                                <li>
                                    If you choose to avail the Third Party Services and you are required to make any payments to the Third Party Providers for such Third Party Services via the Website, you agree and acknowledge that the payment terms of the Third Party Providers will be applicable to such transactions. While, the Company may provide or arrange for technology infrastructure to carry out transactions for Third Party Services, the Company shall not be responsible to you for any of the Third Party Services.
                                </li>
                            </ol>
                        </li>
                        <li>
                            <span class="bold">WEBSITE AVAILABILITY </span><p></p>
                            <ol class="pl-0">
                                <li>
                                    The Company assumes no responsibility and shall not be liable for any damages caused by viruses, trojans or any other form of malware, adware and other malicious programs that may infect your computer system, mobile phone or any hardware or software used by you to access or use the Website or the Services and which may have an adverse impact on your experience of browsing the Website.
                                </li>
                                <li>
                                    If you are dissatisfied with the Website your sole remedy is to discontinue using the Website. You are expected to use adequate anti-virus software and firewalls in your devices to guard against possible attacks by all kinds of malicious software. Further, the Company shall not be responsible for any delays or failures you may have in initiating, conducting, and completing any transactions in connection with the Services.
                                </li>
                                <li>
                                    The Company reserves the right to modify, suspend or withdraw the whole or any part of the Website or any of its contents at any time without any notice or liability.
                                </li>
                            </ol>
                        </li>
                        <li>
                            <span class="bold">REPRESENTATION AND WARRANTIES</span><p></p>
                            <ol class="pl-0">
                                <li>
                                    The information, products and Services are provided on an “AS IS,” “WHERE IS” and “WHERE AVAILABLE” basis. The Company does not warrant the information or Services provided herein, either expressly or impliedly, and expressly disclaims any implied warranties, including but not limited to, warranties of title, noninfringement, merchantability or fitness for a particular purpose. Although the information provided to you is obtained or compiled from sources, we believe to be reliable, the Company cannot and does not guarantee the accuracy, validity, timeliness or completeness of any information or data made available to you for any particular purpose.
                                </li>
                                <li>
                                    None of the information on the Website constitutes a recommendation, solicitation or offer by the Company or its affiliates to buy or sell any securities, futures, options, or other financial instruments of any person or provide any investment advice or service.
                                </li>
                            </ol>
                        </li>
                        <li>
                            <span class="bold">LIMITATION OF LIABILITY</span> <p></p>
                            <ol class="pl-0">
                                <li>
                                    The Company shall not be liable for indirect, incidental, special, exemplary, punitive, or consequential damages, including lost profits, lost data, personal injury, or property damage related to, in connection with, or otherwise resulting from any use of any of the Services.
                                </li>
                                <li>
                                    The Company shall not be liable for any damages, liability or losses arising out of: <p></p>
                                    <ul >
                                        <li>
                                            (a)	your use of or reliance on the Services or your inability to access or use the Services; or
                                        </li>
                                        <li>
                                            (b)	any transaction or relationship between you and any Third-Party Provider.
                                        </li>
                                        <li>
                                            (c)	Any act that is not an obligation of the Company in these User Terms.
                                        </li>
                                        <li>
                                            (d)	Any disclosures made by the Company to any statutory body under any law.
                                        </li>
                                        <li>
                                            (e)	Any loss, notional or otherwise, incurred because of:<p></p>
                                            <ul >
                                                <li>
                                                    (i)	Non-availability or non-accessibility of the Website, electronic payment gateway, telephone(s), or office(s) of the Company for reasons including those beyond the Company’s control.
                                                </li>
                                                <li>
                                                    (ii)	Any inaccuracy or typographical error on the Website or any written, E-mail &amp; SMS communication. The Company specifically disclaims any liability for such inaccuracies or errors.
                                                </li>
                                            </ul>
                                        </li>
                                    </ul>
                                </li>
                                <li>
                                    The Company shall not be liable for delay or failure in performance resulting from causes beyond the Company’s reasonable control. In no event shall the Company’s total liability to you in connection with the Services for all damages, losses and causes of action shall exceed the fee received by the Company from you for making the Services available.
                                </li>
                                <li>
                                    We have taken all reasonable steps to prevent internet fraud and ensure any data collected from you is stored as securely and safely as possible. However, we cannot be held liable in the unlikely event of a breach in our secure computer servers or those of third parties.
                                </li>
                            </ol>
                        </li>
                        <li>
                            <span class="bold">INTELLECTUAL PROPERTY RIGHTS </span><p></p>
                            <ol class="pl-0">
                                <li>
                                    The Company is the sole owner or licensee of all intellectual property rights in the Website, and the materials / contents published therein (excluding the materials and contents published or uploaded by the users of the Website).
                                </li>
                                <li>
                                    Copying, storing, distributing, transmitting, or otherwise modifying any content on the Website other than for your personal, non-commercial use is prohibited and shall amount to an infringement of the intellectual property rights of the Company or the relevant licensor(s) under applicable laws. If you print off, copy, or download any part of the Website in breach of the User Terms, your right to use the Services will cease immediately and you must, at your option, return or destroy any copies of the materials you have made.
                                </li>
                                <li>
                                    All rights not otherwise claimed under the User Terms and Privacy Policy are hereby reserved.
                                </li>
                                <li>
                                    We accept no responsibility for any errors or omissions, or for the results obtained from the use of this information. All information provided on the Website are provided “AS IS” with no guarantee of completeness, accuracy, timeliness or of the results obtained from the use of this information, and without warranty of any kind, express or implied, including, but not limited to warranties of performance, merchantability, and fitness for any particular purpose. Nothing herein shall to any extent substitute for the independent investigations and the sound technical and business judgment of the User(s).
                                </li>
                                <li>
                                    The Company reserves the right, in its sole discretion and without any obligation, to make improvements to, or correct any error or omissions in any portion of the Website.
                                </li>
                            </ol>
                        </li>
                        <li>
                            <span class="bold">CONSENT TO ELECTRONIC COMMUNICATIONS AND TRANSACTIONS</span> <p></p>
                            <ol class="pl-0">
                                <li>
                                    By downloading and / or using the Website, you consent to receiving communications, notices, and information from us electronically, whether sent by e-mail or through other electronic means. Electronic communications shall be deemed to have been received by you when we send the electronic communication at the email address/mobile number provided by you and maintained in our records, or when we post the electronic communication on the Website. Further, you agree that any notice, agreement, disclosure, or other communications that we send to you electronically will satisfy any legal communication requirements, including that such communications be in writing.
                                </li>
                            </ol>
                        </li>
                        <li>
                            <span class="bold">DISCLAIMERS</span> <p></p>
                            <ol class="pl-0">
                                <li>
                                    The contents on the Website are for general information purposes only. Due to the vagaries that can occur in the electronic distribution of information and due to limitations inherent in providing information obtained from multiple sources, there may be delays, omissions, or inaccuracies in the content provided on the Website or delay or errors in the functionality of any or all of the Services. While the Company endeavours to keep the information up to date and correct, we make no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, suitability, or availability thereof for any purpose. Any reliance you place on such information is therefore strictly at your own risk.
                                </li>
                                <li>
                                    Through the Website you may be able to access other websites and / or mobile applications. Such websites and / or mobile applications are not under the control of the Company. We have no control over the nature, content, and availability of those websites / mobile applications. The inclusion of any such links does not necessarily imply a recommendation or endorse the views expressed therein. We reserve the right to disable such access to other websites and / or mobile applications, although we are under no obligation to do so.
                                </li>
                                <li>
                                    Every effort is made to keep the Website up and running smoothly. However, the Company takes no responsibility for, and will not be liable for, the Website being temporarily unavailable due to technical issues beyond our control. Further, the Website may be subject to upgradation, as and when required and therefore, some functions and features may not be fully operational during those periods.
                                </li>
                                <li>
                                    You acknowledge and agree that at no time are the Company is making any representation or warranty regarding any services provided by a Third-Party Provider nor will we be liable to you or any such Third-Party Provider for any consequences or claims arising from or in connection with the goods provided by such Third Party Provider. You hereby disclaim and waive any rights and claims you may have against us with respect to services of a Third-Party Provider.
                                </li>
                                <li>
                                    In no event will we or our employees, affiliates, authors, or agents be liable to you or any third party for any decision made or action taken by your reliance on the contents on the Website.
                                </li>
                                <li>
                                    In the event the Website is accessed from outside India, it shall be entirely at your risk. If you choose to access or use the Website from or in locations outside India, you shall be responsible for ensuring compliance of applicable laws, regulations, byelaws, licenses, registrations, permits, authorizations, rules, and guidelines.
                                </li>
                            </ol>
                        </li>
                        <li>
                            <span class="bold">CHOICE OF LAW AND DISPUTE RESOLUTION </span><p></p>
                            <ol class="pl-0">
                                <li>
                                    The User Terms, the Privacy Policy and your use of the Website shall be governed by, and construed in accordance with, the laws of India, including without limitation the Indian Contract Act, 1872, Information Technology Act, 2000 and the rules, regulations, guidelines and clarifications framed thereunder (including the Information Technology (Reasonable Security Practices and Procedures and Sensitive Personal Information) Rules, 2011 and the Information Technology (Intermediaries Guidelines) Rules, 2011) and without reference to principles of conflicts of law.
                                </li>
                                <li>
                                    All disputes, differences or claims arising out of or in connection with your use of the Website or the Services shall be referred to and finally resolved by arbitration in accordance with the (Indian) Arbitration and Conciliation Act, 1996, which is deemed to be incorporated by reference in this clause 14.2. If either you or the Company (“<span class="bold">Complainant Party</span>”) seeks to commence arbitration under this clause 14.2, the Complainant Party shall first serve a written notice, specifying the matter or matters to be so submitted to arbitration, to the party against whom arbitration is sought to be commenced. The seat and venue of such arbitration shall be in Bengaluru and all proceedings shall be conducted in the English language.
                                </li>
                                <li>
                                    The number of arbitrators shall be three. One arbitrator shall be appointed by the Company and one arbitrator shall be appointed by you and together the two arbitrators so appointed shall appoint the third arbitrator. No officer, director, shareholder, employee, representative or relative of either the Company or you may be nominated or appointed as an arbitrator. In the event the arbitral tribunal cannot be constituted in accordance with this clause within 30 days from a Party serving notice of arbitration under clause, the arbitral tribunal shall be constituted in accordance with the (Indian) Arbitration and Conciliation Act, 1996.
                                </li>
                                <li>
                                    All claims and counterclaims shall, to the extent such claims or counterclaims are known at the time any arbitration is commenced, shall be consolidated, and determined in the same arbitration proceedings.
                                </li>
                                <li>
                                    The award rendered by the arbitrator or arbitrators shall be final, conclusive, and binding on all parties to the dispute and shall be subject to execution in any court of competent jurisdiction.
                                </li>
                                <li>
                                    Each Party shall co-operate in good faith to expedite, to the maximum extent practicable, the conduct of any arbitral proceedings commenced under these User Terms.
                                </li>
                                <li>
                                    Nothing shall preclude any Party from seeking interim or permanent equitable or injunctive relief, or both, from the competent courts, having jurisdiction to grant relief on any disputes or differences arising from the use of the Website, or the Services. The pursuit of equitable or injunctive relief shall not be a waiver of the duty of the parties to pursue any remedy (including for monetary damages) through arbitration as described in this clause 14.
                                </li>
                                <li>
                                    The courts or tribunals at Bangalore shall have exclusive jurisdiction over any dispute arising from or relating to the User Terms, Privacy Policy, or your use of the Services. You expressly consent to the jurisdiction of the said courts / tribunal and irrevocably waive any objection now or in future, to such jurisdiction based on forum non-convenience or any other basis.
                                </li>
                            </ol>
                        </li>
                        <li>
                            <span class="bold">INDEMNITY </span><p></p>
                            <ol class="pl-0">
                                <li>
                                    You agree to defend, indemnify and hold harmless the Company, its affiliates, independent contractors, service providers, consultants, licensors, agents and representatives, and each of their respective directors, officers and employees, from and against any and all claims, losses, liability, damages, and/or costs (including, but not limited to, reasonable attorney fees and costs) arising from or related to (a) your access to or use of the Website; (b) your violations of the User Terms; (c) your violation of any rights of any third party, including infringement of their intellectual property right; and / or (d) your conduct in connection with the Services.
                                </li>
                            </ol>
                        </li>
                        <li>
                            <span class="bold">SEVERABILITY</span> <p></p>
                            <ol class="pl-0">
                                <li>
                                    If any provision of the User Terms, including the Privacy Policy is deemed invalid, unlawful, void or for any other reason unenforceable, then that provision shall be deemed severable from the User Terms and shall not affect the validity and enforceability of any of the remaining provisions.
                                </li>
                            </ol>
                        </li>
                        <li>
                            <span class="bold">GENERAL CONDITIONS</span> <p></p>
                            <ol class="pl-0">
                                <li>
                                    We may subcontract any part or parts of the Services that we provide to you from time to time and we may assign or novate any part or parts of our rights under the User Terms and Privacy Policy without your consent or any requirement to notify you.
                                </li>
                                <li>
                                    Users shall not collect or harvest any personally identifiable information from the Website, use communication systems provided by the Website for any commercial solicitation purposes, solicit for any reason whatsoever any Users of the Website with respect to their submissions to the Website, or publish or distribute any vouchers or codes in connection with the Website, or scrape or hack the Website.
                                </li>
                                <li>
                                    No delay or failure on our part to enforce our rights or remedies under the User Terms and Privacy Policy shall constitute a waiver on our part of such rights or remedies unless such waiver is confirmed in writing.
                                </li>
                                <li>
                                    The rule of construction, if any, that a contract should be interpreted against the parties responsible for the drafting and preparation thereof shall not apply.
                                </li>
                                <li>
                                    All dealings, correspondence, and contacts between us shall be made or conducted in the English language.
                                </li>
                            </ol>
                        </li>
                        <li>
                            <span class="bold">COMPLAINTS</span> <p></p>
                            <ol class="pl-0">
                                <li>
                                    We are committed to provide excellent user experience. Therefore, we attend to User complaints with diligence. We aim to respond to your complaints within 14 working days. All complaints and feedback should be addressed to the following email ID contact@bengalurufc.com
                                </li>
                            </ol>
                        </li>
                    </ul>
                </div>


            </div>
        </>
    )
}

export default T_C
